# fly.toml app configuration file generated for mvh-ts-exit on 2023-09-17T11:52:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mvh-ts-exit"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]

[build]

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641

  [[services.ports]]
    port = 41641
