# fly.toml file generated for mvh-ts-exit on 2023-02-21T08:20:29-06:00

app = "mvh-ts-exit"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "41641"

[experimental]
  auto_rollback = false
  private_network = true

[[services]]
  internal_port = 41641
  protocol = "udp"

  [[services.ports]]
    port = "41641"
